apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31112